### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by popov895** [comment]
Reverted. Wrong file location.

**Comment by popov895** [comment]
Please place the file into the `po` folder and try again.

**Comment by Vistaus** [comment]
I did place it in the po folder as I always do, but GitHub was apparently having a bad day. First it uploaded it to the wrong folder, which GitHub never does, and just now it took me about six tries before it accepted the po file again. :/ But it should be good now.

**Comment by popov895** [comment]
Can you create a new PR?

**Comment by Vistaus** [comment]
Sure thing.

**Pull request merged**
