### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by psjnek**

### CODE REVIEW

**Comment by popov895** [comment]
Sorry, but I can't merge your PR. Please, rebase it onto the main branch of this repository.

**Comment by psjnek** [comment]
> Sorry, but I can't merge your PR. Please, rebase it onto the main branch of this repository.

Ok, I will do that tomorrow.

**Comment by psjnek** [comment]
> Sorry, but I can't merge your PR. Please, rebase it onto the main branch of this repository.

@popov895 
How do I do that?

**Comment by popov895** [comment]
Do you know how to work with Git on the command line?

**Comment by psjnek** [comment]
> Do you know how to work with Git on the command line?

Not really. I always used GitHub Desktop.

**Comment by popov895** [comment]
Open your Clipman repository in GitHub Desktop and execute `Repository` > `Open in Git Bash` in the menu. Any success?

**Comment by psjnek** [comment]
> Open your Clipman repository in GitHub Desktop and execute `Repository` > `Open in Git Bash` in the menu. Any success?

Yep, it is called "Open in GNOME Terminal on Fedora".

**Comment by psjnek** [comment]
Do I need to resolve these conflicts btw?

image

**Comment by popov895** [comment]
In the terminal run the following command:
```
git remote -v
```

**Comment by popov895** [comment]
What it prints?

**Comment by psjnek** [comment]
> What it prints?

```bash
[websnke@fedora Clipman]$ git remote -v
origin	https://github.com/WebSnke/Clipman.git (fetch)
origin	https://github.com/WebSnke/Clipman.git (push)
upstream	https://github.com/popov895/Clipman.git (fetch)
upstream	https://github.com/popov895/Clipman.git (push)
[websnke@fedora Clipman]$ 
```

**Comment by popov895** [comment]
Great. In the terminal run the following commands:
```
git checkout main
git fetch upstream
git reset --hard upstream/main
git push -f
```
When executing some commands, you will be asked to enter your GitHub password.

**Comment by psjnek** [comment]
> Great. In the terminal run the following commands:
> 
> ```
> git checkout main
> git fetch upstream
> git reset --hard upstream/main
> git push -f
> ```
> 
> When executing some commands, you will be asked to enter your GitHub password.

Ok, done. Thanks for walking me through the steps.

**Comment by popov895** [comment]
Great. And please use a separate branch for PR in the future.

**Comment by psjnek** [comment]
> Great. And please use a separate branch for PR in the future.

Isn't main-1 a separate branch?

**Comment by popov895** [comment]
No. It's a `main` branch of your forked Clipman repository. See [here](https://lovelacecoding.hashnode.dev/how-to-create-a-pull-request-with-github-desktop) how to create a PR from the GitHub Desktop.

**Pull request closed without merging**
